services:
  ocr:
    build: 
      context: .
      dockerfile: dev-dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/ocr
    restart: no
    command: "/bin/sh -c 'poetry install && poetry run fastapi dev ocr/api.py --host 0.0.0.0 --port 8000'" 
  frontend:
    build:
      context: ./frontend
      dockerfile: dev-dockerfile
    ports:
      - "5173:5173"
      - "8080:8080"
    volumes:
      - ./frontend:/app
    restart: no
    command: "/bin/sh -c 'npm install && npx playwright install && npx playwright test --ui-port=8080 --ui-host=0.0.0.0 & npm run dev -- --host'" 
    
