name: Deploy ReportVision Frontend
description: Promote API from secondary slot, and deploy frontend from tarball
inputs:
  deploy_env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
  frontend_tarball:
    description: The path to the tar file containing the frontend code to deploy
    required: true
  azure_client_id:
    description: The Azure client_id for this environment.
    required: true
  azure_tenant_id:
    description: The Azure tenant_id for this environment.
    required: true
  azure_subscription_id:
    description: The Azure subscription_id for this environment.
    required: true

runs:
  using: composite
  steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
    - name: Retrieve frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-tarball
    - name: Unpack frontend tarball
      shell: bash
      run: |
        mkdir frontend-build;
        tar -C frontend-build -zxvf ${{ inputs.frontend_tarball }}
    - name: Deploy frontend to Azure Blob Storage
      shell: bash
      run: |
        az storage blob upload-batch -s frontend-build/ -d '$web' \
        --account-name reportvisionfrontend${{ inputs.deploy_env }} \
        --overwrite
    - name: Azure logout
      shell: bash
      run: |
        az logout