name: Build ReportVision's Front End
description: Build the React application
inputs:
  deploy_env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
  frontend_tarball:
    description: The path to the tar file containing the client code to deploy
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Use cache for node_modules
      uses: actions/cache@v4
      with:
        path: |
          ./OCR/frontend/node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('OCR/frontend/package.json') }}
    - name: Install dependencies
      working-directory: ./OCR/frontend
      shell: bash
      run: |
        npm ci
    - name: Build deployable frontend
      shell: bash
      working-directory: ./OCR/frontend
      env:
        DEPLOY_ENV: ${{ inputs.deploy_env }}
      run: |
        npm run build 
    - name: Test frontend
      shell: bash
      working-directory: ./OCR/frontend
      env:
        DEPLOY_ENV: ${{ inputs.deploy_env }}
      run: |
        npm run test
    - name: Pack frontend into a tarball
      shell: bash
      run: |
        tar -C ./OCR/frontend/build -czf ${{ inputs.frontend_tarball }} .
    - name: Upload frontend build files
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: frontend-tarball
        path: ${{ inputs.frontend_tarball }}
        retention-days: 1