name: Terraform Action Deployment
description: Build and push Docker image to the registry
inputs:
  deploy_env:
    description: The environment to deploy to
    required: true
  token:
    description: Github Token
    required: true
  version:
    description: ocr-api version
    required: true

runs:
  using: composite
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ inputs.token }}
      - name: Lowercase the repo name
        shell: bash
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./OCR/
          file: ./OCR/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ inputs.version }}