name: Terraform Action Deployment
description: Build and push Docker image to the registry
inputs:
  deploy_env:
    description: The environment to deploy to
    required: true
  token:
    description: Github Token
    required: true
  username:
    description: Github Token
    required: true
runs:
  using: composite
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lowercase the repo name
        shell: bash
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Login to ACR
        shell: bash
        run: docker login ${{ env.REGISTRY }} -u ${{ inputs.username }} -p ${{ inputs.token }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./OCR/
          file: ./OCR/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ env.VERSION }}