name: Build OCR exec
on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.build.outputs.output_artifacts }}
    # push:
    #     branches:
    #       - idwa-ocr-ci-for-executable
    #     paths:
    #       - .github/workflows/release-ocr.yml
    #       - .github/workflows/build-ocr.yml
    #       - OCR/**
      
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos
            cmd: >
              pyinstaller -F -w -n main ./OCR/ocr/main.py &&
              cd dist/
            out_file: main-macos
          - os: windows-latest
            name: windows
            cmd: pyinstaller -F -w -n main ./OCR/ocr/main.py
            out_file: main-windows
          - os: ubuntu-latest
            name: ubuntu
            cmd: >
              pyinstaller -F -w -n main ./OCR/ocr/main.py &&
              cd dist/
            out_file: main-ubuntu
    runs-on: ${{ matrix.os }}
    outputs:
      output_artifacts: ${{ steps.artifacts.outputs.matrix.out_file }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
          pip install docopt
      - name: build executable
        run: ${{ matrix.cmd }}
      - uses: actions/upload-artifact@v4
        id: artifacts
        with:
          name: main-${{ matrix.name }}
          path: ./dist/${{ matrix.out_file}}
