name: Build OCR exec
on:
    push:
        branches:
          - idwa-ocr-ci-for-executable
        paths:
          - .github/workflows/build-ocr.yml
          - OCR/**
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos
            cmd: >
              pyinstaller ./OCR/ocr/main.py -F -w
              cd dist/ &&
              zip -r9 main main
            out_file: main.zip 
          - os: windows-latest
            name: windows
            cmd: pyinstaller ./OCR/ocr/main.py -F -w
            out_file: main.exe
          - os: ubuntu-latest
            name: ubuntu
            cmd: >
              pyinstaller ./OCR/ocr/main.py -F -w
              cd dist/ &&
              zip -r9 main main
            out_file: main.zip


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
          pip install docopt
      - name: build executable
        run: ${{ matrix.cmd }}
      - uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.name }}
          path: dist/main