name: Build OCR exec
on:
    push:
        branches:
          - idwa-ocr-ci-for-executable
        paths:
          - .github/workflows/build-ocr.yml
          - OCR/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: build executable
        run: pyinstaller ./OCR/ocr/main.py --add-data=./OCR/ocr/assets/form_filled.png:assets/ --add-data=./OCR/ocr/assets/form_segmention_template.png:assets --add-data=./OCR/ocr/assets/labels.json:assets/
      - uses: actions/upload-artifact@v3
        with:
          name: main
          path: ./dist/main