name: Build & Upload OCR Binaries
on:
  push:
    branches:
      - rm-unused-code
  # workflow_call:
  #   outputs:
  #     output-file:
  #       description: "The first output string"
  #       value: ${{ jobs.build.outputs.output_artifacts }}
  # workflow_dispatch:
      
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos
            cmd: >
              cd OCR/ &&
              poetry run build &&
              cd dist/ &&
              zip -r9 main-macos main
            out_file: main-macos.zip
          - os: windows-latest
            name: windows
            cmd: >
              cd OCR/ &&
              poetry run build &&
              7z a main-windows main.exe
            out_file: main-windows.zip
          - os: ubuntu-latest
            name: ubuntu
            cmd: >
              cd OCR/ &&
              poetry run build &&
              cd dist/ &&
              zip -r9 main-ubuntu main
            out_file: main-ubuntu.zip
    runs-on: ${{ matrix.os }}
    outputs:
      output_artifacts: ${{ steps.artifacts.outputs.matrix.out_file }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd OCR/
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Build binaries for all OS's
        run: ${{ matrix.cmd }}
      - name: Upload Artifacts To Workflow
        uses: actions/upload-artifact@v4
        id: artifacts
        with:
          name: main-${{ matrix.name }}
          path: ./OCR/dist/${{ matrix.out_file}}
