name: Build OCR exec
on:
    push:
        branches:
          - idwa-ocr-ci-for-executable
        paths:
          - .github/workflows/build-ocr.yml
          - OCR/**
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        inlude:
          - os: ubuntu-latest
            name: ubuntu
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
          pip install docopt
      - name: build executable
        run: pyinstaller ./OCR/ocr/main.py -F -w
      - uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.os.name }}
          path: dist/main