name: Create, publish, deploy a OCR API image

on:
  push:
    branches: check-run-deploy-without-build-ocr

env:
  REGISTRY: ghcr.io
  VERSION: derek-main-dev


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      result: ${{ steps.image_check.outputs.result}}  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    #   - name: Check image
    #     id: image_exists
    #     uses: cloudposse/github-action-docker-image-exists@main
    #     with:
    #       registry: ghcr.io
    #       organization: "cdcgov"
    #       repository: "reportvision-ocr-api"
    #       login: "${{ github.actor }}"
    #       password: "${{ secrets.GITHUB_TOKEN }}"
    #       tag: latest
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Check if image exists
        id: image_check
        run: docker manifest inspect ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ env.VERSION }} > /dev/null ; echo $?
      - name: Build and push Docker image
        id: push
        if: steps.image_check.outcome == 1
        uses: docker/build-push-action@v6
        with:
          context: ./OCR/
          file: ./OCR/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: dev
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: reportvision-ocr-api-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.REGISTRY }}/${{ env.REPO}}-ocr-api:${{ env.VERSION }}'
      
