name: Create, publish, deploy a OCR API image

on:
  push:
    branches: temp-ocr-deploy

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # VERSION: ${{ inputs.tag }}
  VERSION: test-deploy-1

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./OCR/
          file: ./OCR/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}-ocr-api:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: dev
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: reportvision-ocr-api-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO}}:${{ env.VERSION }}'
      
