name: Build and Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - dev2
          - dev3
          - dev4
          - dev5
          - dev6

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 20

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-frontend
        name: Build front-end application
        with:
          frontend_tarball: ./frontend.tgz
          deploy_env: ${{ inputs.deploy_env }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Promote and deploy
        uses: ./.github/actions/deploy-application
        with:
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          frontend_tarball: frontend.tgz
          deploy_env: ${{ inputs.deploy_env }}