name: Build and Deploy full app

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - dev2
          - dev3
          - dev4
          - dev5
          - dev6
      ocr-version:
        description: 'The environment to deploy to'
        required: true

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 20
  REGISTRY: ghcr.io


jobs:
  build_publish_ocr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push backend
        uses: ./.github/actions/build-publish-ocr
        with:
          deploy_env: ${{ inputs.deploy_env }}
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.ocr-version }}

  build_frontend:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-frontend
        name: Build front-end application
        with:
          frontend_tarball: ./frontend.tgz
          deploy_env: ${{ inputs.deploy_env }}