name: Deploy site

on:
  workflow_run:
    workflows: ["Build Frontend"]
    branches: [GHA-react-build-to-blob]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.MAIN_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.MAIN_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.MAIN_AZURE_SUBSCRIPTION_ID }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name craazstoragedemo48765 -d '$web' -s ./production-files
    
    - name: Azure logout
      run: |
            az logout