name: Run Tests

on:
    push:
        branches:
            - frontend-tests-GHA
    # pull_request:
    #     paths:
    #     - .github/workflows/frontend-tests.yml
    #     - OCR/frontend/**
    
jobs:
  vitests:
    runs-on: macos-latest
    defaults:
        run:
          working-directory: OCR/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Vitests
        run: |
            npm run test
  playwright-tests:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: OCR/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
            npm ci
            npx playwright install --with-deps
      - name: Run playwright tests
        run: npx playwright test