name: Add issues to repo projects
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  add-to-dedupe-project:
    if: contains(github.event.issue.labels.*.name, 'dedupe')
    name: Add issue to dedupe project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/CDCgov/projects/34
          github-token: ${{ secrets.ASSIGN_ISSUES_TO_PROJECTS }} #this custom action doesn't allow the default GITHUB_TOKEN, it requires us to use a PAT as the secret unfortunetly..
  add-to-ocr-project:
    if: contains(github.event.issue.labels.*.name, 'OCR')
    name: Add issue to the ocr project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/CDCgov/projects/33
          github-token: ${{ secrets.ASSIGN_ISSUES_TO_PROJECTS }} #this custom action doesn't allow the default GITHUB_TOKEN, it requires us to use a PAT as the secret unfortunetly..
