name: OCR Poetry Tests
on:
  # pull_request:
  #   types: [opened, reopened]
  #   paths:
  #     - .github/workflows/ocr-tests.yml
  #     - OCR/**
  push:
    branches: ["idwa-ocr-58-fix-test-trigger"]
    paths:
      - 'OCR/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: OCR
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Run tests
        run: poetry run pytest
