name: Release MDE-OCR artifacts
run-name: Release MDE-OCR artifacts - by @${{ github.actor }}
on:
    # workflow_dispatch:
    #     inputs:
    #         tag:
    #             description: 'target environment'
    #             required: true
    push:
        branches:
          - idwa-ocr-ci-for-executable
        paths:
          - .github/workflows/release-ocr.yml
          - .github/workflows/build-ocr.yml
          - OCR/**
        # tags:
        #     - 'v*'
jobs:
  create-release:
    name: Create Release
    
    runs-on: [ubuntu-latest]
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/v0.1.3',
                sha: context.sha
            })
    - name: Create release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: v0.1.3
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="MDE-OCR ${tag#v}" \
            --generate-notes
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Upload Artifacts To Workflow
      uses: actions/upload-artifact@v4
      with:
        name: release_url
        path: release_url.txt
#   build-release:
#     uses: ./.github/workflows/build-ocr.yml
  upload-release-asset:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name:
          run: |
            mkdir artifacts &&
            cd ./artifacts
            touch main-macos.txt && echo "hello\\world > main-macos.txt"
        - name: ls
          run: ls
        # - name: Download Artifacts To Job
        #   uses: actions/download-artifact@v4
        #   with:
        #     path: artifacts
        #     merge-multiple: true
        - name: Upload release binaries
          uses: alexellis/upload-assets@0.4.1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            asset_paths: '["./artifacts/*"]'