name: Release MDE-OCR artifacts
run-name: Release MDE-OCR artifacts - by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Version tag for new release'
                required: true
jobs:
  create-release:
    name: Create Release
    runs-on: [ubuntu-latest]
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create tag
      uses: actions/github-script@v7
      with:
        script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ github.event.inputs.tag }}',
                sha: context.sha
            })
    - name: Create release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="MDE-OCR ${tag}" \
            --generate-notes
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Upload Artifacts To Workflow
      uses: actions/upload-artifact@v4
      with:
        name: release_url
        path: release_url.txt
  build-release:
    uses: ./.github/workflows/build-ocr.yml
  upload-release-asset:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Download Artifacts To Job
          uses: actions/download-artifact@v4
          with:
            path: artifacts
            merge-multiple: true
        - name: Release Upload Assets
          uses: jaywcjlove/github-action-upload-assets@main
          with:
            tag: ${{ github.event.inputs.tag }}
            asset-path: '["./artifacts/*"]'
